# Generated by Django 6.0.3 on 2026-04-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='llamado',
            field=models.BooleanField(default=False, verbose_name='Llamado'),
        ),
        migrations.AddField(
            model_name='turno',
            name='llamado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Llamado en'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de documento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('Pasaporte', 'Pasaporte')], max_length=20, null=True, verbose_name='Tipo de documento'),
        ),
    ]
